name             'lamp-server'
maintainer       'The OpenGov Foundation'
maintainer_email 'developers@opengovfoundation.org'
license          'CC0'
description      'Installs/Configures a LAMP server'
long_description 'Installs/Configures a LAMP server'
version          '0.1.0'

depends 'mariadb'
depends 'mysql'
depends 'apache2'
depends 'git'
